version: '3.4'

networks:
    localdev:
        name: localdev

services:
    pizzaparadise.blazor:
        image: ${DOCKER_REGISTRY-}pizzaparadiseblazor
        build:
            context: .
            dockerfile: PizzaParadise.Blazor/Dockerfile
        ports:
            - "7000:80"
        depends_on:
            - dbserver
        networks:
            - localdev
        environment:
            ConnectionStrings__PizzaParadiseDb: "Server=host.docker.internal,1400;Database=PizzaParadiseDb;User=sa;Password=password123"
            SeqUri: "http://host.docker.internal:5001"
            Serilog__WriteTo__1__Args__serverUrl: "http://host.docker.internal:5001"

    dbserver:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: dbserver
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=password123
            - MSSQL_TCP_PORT=1433
        ports:
            - "1400:1433"
        networks:
            - localdev
        volumes:
            - ./dbserver:/var/lib/sql/data

    seq:
        image: datalust/seq:latest
        container_name: seq
        environment:
            - ACCEPT_EULA=Y
        ports:
            - "5000:80"
            - "5001:5341"
        networks:
            - localdev
        volumes:
            - ./seq:/var/lib/seq/data